### ISSUE TITLE
Exercícios Importados

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#31]
Exercícios importados estão salvando a resposta sempre como alternativa A

**Comment by flespindola** [comment]
Fiz uma alteração. Por favor verifica exatamente o padrão do arquivo usado e confirma se o erro persiste.

**Comment by RodolfoXYZ** [comment]
O erro persiste. E, caso não preencha até a alternativa (E), o exercício importado utiliza o enunciado da questão como alternativa número 1.
Além disso, as alternativas são renomeadas para 0, 1, 2, 3, 4, respectivamente.
![image](https://user-images.githubusercontent.com/123428706/228598264-32b491ee-9f54-4e11-8e20-c164f16b1bf6.png)

**Comment by flespindola** [comment]
Rodolfo, me manda o arquivo que tais usando por favor
