### ISSUE TITLE
Atualizar informações (avaliação)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#32]
Link: https://educamaisdev.com/testing/edit/60
Descrição do Problema: Estoura erro na tela ao clicar no botão de atualizar as informações da avaliação.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/228599952-88c88e17-dca5-4b9b-ac19-8bfe276b5d86.png)

**Comment by flespindola** [comment]
Rodolfo, testa se a data está sendo atualizada de maneira correta, fiz uma alteração mas pode haver um erro que salva a data 1 dia anterior à data escolhida

**Comment by RodolfoXYZ** [comment]
Testando agora
