### ISSUE TITLE
Colagem de texto

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#35]
Link: https://educamaisdev.com/exercises/create
Descrição: Existem duas opções de colagem, uma com formatação, e outra sem formatação. 
Entretanto, a opção de colar importando a formatação, só está absorvendo formatações específicas como o negrito.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/229124925-4a6105d6-9a6d-4b58-a348-7c7d80884db1.png)

**Comment by flespindola** [comment]
Esse é um feature da biblioteca que estamos usando, ai não temos acesso direto para mexer nesses itens, a não ser remover ou incluir essas opções. As formatações não incluídas é porque de alguma forma não são suportadas pelo editor.
