### ISSUE TITLE
Inativar Município

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#38]
Link: https://educamaisdev.com/admin/cities/show/1
Descrição: Botão de inativar município não funciona e nem aparece na lista de municípios, só após abrir o município
Imagem: ![image](https://user-images.githubusercontent.com/123428706/229519742-4b5a3fe7-3d18-43f0-b4ce-fe8d28f60a19.png)

**Comment by flespindola** [comment]
Removi o botão de editar e substitui o inativar pelo editar, pois desativar um município implica em muitas questões em cascata, das escolas, atividades, usuários etc. Fica mais viável planejar depois a real necessidade de um botão de desativar município que desativa tudo, como um botão de alto impacto no sistema
