### ISSUE TITLE
Criação de Avaliação

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#4]
Avaliação só deve ser criada após o usuário preencher todas as informações. Atualmente é possível criar uma avaliação apenas com o título preenchido.

**Comment by RodolfoXYZ** [comment]
Descrição: ainda é possível criar uma avaliação usando uma data inexistente.
![image](https://user-images.githubusercontent.com/123428706/232056928-2cd0c52b-a3fb-48cc-9a03-e9835b15f9eb.png)

**Comment by flespindola** [comment]
Como foi criada a avaliação? Não havia o calendário lá no modal dos dados iniciais?
