### ISSUE TITLE
Alterar senha

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#40]
Link: https://educamaisdev.com/profile/edit/1080
Descrição: Não é possível alterar senha dos usuários, nem mesmo usando o usuário administrador.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/229522349-337c0f42-7a39-4439-9d50-dc64bc6d86a3.png)

**Comment by flespindola** [comment]
É feito exclusivamente pela recuperação de senha, chegando ao email
