### ISSUE TITLE
Mais Informações (Municípios)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#45]
Link: https://educamaisdev.com/admin/cities
Descrição: Botão de mais informações na aba de Municípios não redireciona para lugar nenhum.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/229539489-713a8a5c-d0a7-4d85-adf1-75c832dd32b3.png)

**Comment by flespindola** [comment]
Botão sem uso, foi retirado.
