### ISSUE TITLE
Foto do Perfil (Escola)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#51]
Link: https://educamaisdev.com/admin/schools/edit/67
Descrição: Foto de perfil da escola não salva.

**Comment by flespindola** [comment]
Ela está salvando sim, só ainda não está sendo apresentada em nenhum lugar. Na página de edição, o input que recebe o arquivo não trás de volta o arquivo salvo porque para type="file" isso não se faz necessário. Em uma página posterior que for usar a foto do perfil da escola, ela estará disponível.
