### ISSUE TITLE
Coluna de Escola (Usuários)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#56]
Link: https://educamaisdev.com/users
Descrição: Adicionar uma coluna contendo a escola em que cada aluno está registrado.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/229910456-14ecc707-00b6-4ad0-8ad4-ee5a8acadc1f.png)

**Comment by flespindola** [comment]
Nessa lista não aparecerá alunos por enquanto, os que estão aparecendo são residuais antes de separarmos as aplicações. Assim que iniciarmos o periodo de relatórios, ficará mais viável produzir uma tela com tudo ou telas separadas entre alunos e professores. Por enquanto, essa página lista professores e admins e mostra a escola do professor.
