### ISSUE TITLE
Criação de Usuário (Aluno)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#58]
Descrição: ao tentar criar um usuário de aluno dentro de uma escola, as turmas não aparecem para serem selecionadas na lista.
Ao criar usuário aluno pela guia de usuários, não é possível designar o usuário para escola nenhuma.
Após criar um usuário dentro de uma escola, você é redirecionado para a guia de usuários, e não para a escola onde você estava navegando anteriormente.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/230091270-dfdf3380-21e2-4ab0-ac23-01d93fdcad4f.png)
![image](https://user-images.githubusercontent.com/123428706/230091306-02ad189c-da4e-45ba-93c9-87cfa4ff69a3.png)

**Comment by flespindola** [comment]
Aqui apareceu. Tem certeza que as turmas da escola no contexto estão ativas?

<img width="1440" alt="Captura de Tela 2023-04-05 às 15 13 05" src="https://user-images.githubusercontent.com/95312656/230107828-c843afcd-34e4-441d-9c7a-4c2ae484f1cd.png">

**Comment by flespindola** [comment]
<img width="1440" alt="Captura de Tela 2023-04-05 às 15 14 49" src="https://user-images.githubusercontent.com/95312656/230108281-c86fc7d2-e540-4914-b0ab-c43992cfa6fb.png">
