### ISSUE TITLE
Alteração de cargo (gestor)

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#63]
Descrição: erro ao atualizar cargo para gestor.
Imagem: 
![image](https://user-images.githubusercontent.com/123428706/230181012-72a1f68f-9475-467d-af24-5cacc4595972.png)

**Comment by flespindola** [comment]
O problema estava relacionado a data, mas de qualquer forma desativei o select "Tipo de usuário" pois vamos gerenciar isso melhor posteriormente
