### ISSUE TITLE
Acesso ao Sistema

### ISSUE THREAD

**Issue by RodolfoXYZ** [flespindola/educa#9]
Usuário vinculado a uma escola inativa consegue acessar o sistema.

**Comment by RodolfoXYZ** [comment]
Usuário ainda consegue fazer alterações nos cadernos e deletar materiais.

**Comment by flespindola** [comment]
Como expliquei no comentário anterior. Para inativar o acesso do usuário, precisamos suspender o usuário. Os cadernos e materiais criados por ele, pertencem ao usuário dele, por isso deve ser o usuário desativado.
